apiVersion: v1
kind: Service
metadata:
  labels:
    app: manta-backend
  name: manta-backend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: manta-backend
  type: LoadBalancer
