apiVersion: v1
kind: Service
metadata:
  labels:
    app: manta-frontend
  name: manta-frontend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: manta-frontend
  type: LoadBalancer
